#!/bin/bash
 
### BEGIN INIT INFO
# Provides:                     nodejs
# Required-Start:               $local_fs
# X-UnitedLinux-Should-Start:
# Required-Stop:                $local_fs
# X-UnitedLinux-Should-Stop:
# Default-Start:                2 3 4 5
# Default-Stop:                 0 1 6
# Short-Description:            nodejs
# Description:                  nodejs
### END INIT INFO

export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in  
    start)
        su - pi -c "forever start --append --watch --watchDirectory=/home/pi/nodejs/temperature -l /var/log/temperature.log --spinSleepTime 5000 --sourceDir=/home/pi/nodejs/temperature app.js"  
        ;;
    stop)
        su - pi -c "forever stopall"
        ;;
    restart)
        su - pi -c "forever restartall"
        ;;
    status)
        su - pi -c "forever list"
        ;;
esac  
